### ISSUE TITLE
Swagger example request with frombody attr

### ISSUE THREAD

**Issue by ivpadim** [FastEndpoints/Library#195]
I have the following setup and I'm having trouble with the swagger doc.

```csharp
public record MyRecord(string Name, string Value);

public class MyRequest
{
  [FromBody]
  public IEnumerable<MyRecord> Records {get;set;}
  
  [FromClaim(ClaimTypes.NameIdentifier, IsRequired = true)]
  public string UserName {get;set;}
}

//Endpoint code
public override void Configure() {
   Summary(s =>
   {
       s.ExampleRequest = new MyRequest() { Records = new List<MyRecord>() { new ("Name 1","Value 1")} };
   });
}
```

The body should appear as

```json
[
 { 
   "name": "Name 1", 
   "value": "Value 1"
 }
]
```

But its appearing as:

```json
{
  "records":
    [
     { 
       "name": "Name 1", 
       "value": "Value 1"
     }
    ]
}
```

If I provide a list of objects in the ExampleRequest I get an error so I can only provide a Request.

**Comment by dj-nitehawk** [comment]
thanks for reporting. fixed in `v5.0.0-beta6`. see upgrade notes [here](https://github.com/FastEndpoints/Library/blob/main/Src/Library/changelog.md#breaking-changes).
however it is mandatory to provide an  `ExampleRequest` when dealing with records, because FE doesn't know how to create an instance of your record, due to the lack of a parameterless ctor.
```cs
Summary(s =>
{
    s.ExampleRequest = new[] {
        new MyRecord("one", "val 1"),
        new MyRecord("two", "val 2")
    };
});
```

**Comment by ivpadim** [comment]
Thanks is working now!

**Comment by vpetrusevici** [comment]
@dj-nitehawk  Looks like it still doesn't work for openapi3 (tested with yaml)
![image](https://user-images.githubusercontent.com/40790510/188719658-281f8709-8520-4b26-b3c8-38f046361fe5.png)
![image](https://user-images.githubusercontent.com/40790510/188719731-225c7925-bd4d-4d79-94b8-6ff891e3883e.png)
Also tried with string field.
Checked on versions 5.0.0 and 5.1.0-beta9

**Comment by dj-nitehawk** [comment]
@vpetrusevici make sure you're using `FastEndpoints.FromBody` and not the one from mvc.

**Comment by vpetrusevici** [comment]
I just used AddOpenApiDocument instead of AddSwaggerDoc. :)
