### ISSUE TITLE
Exception thrown randomly when testing.

### ISSUE THREAD

**Issue by szekelymatyas** [FastEndpoints/Library#224]
Im using xUnit and WebApplicationFactory to create a test server. I wrote some test. When I run all one or two randomly fails. Run again and they succeed.

Here is my exception:

```
Message: 
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.

  Stack Trace: 
Enumerator.MoveNextRare()
Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
EndpointDefinition.<PostProcessors>b__139_0(IGlobalPostProcessor p)
WhereArrayIterator`1.MoveNext()
List`1.InsertRange(Int32 index, IEnumerable`1 collection)
EndpointDefinition.PostProcessors(IGlobalPostProcessor[] postProcessors)
<>c__DisplayClass0_0.<<Main>$>b__7(EndpointDefinition ep) line 58
MainExtensions.MapFastEndpoints(IEndpointRouteBuilder app, Action`1 configAction)
MainExtensions.UseFastEndpoints(WebApplication app, Action`1 configAction)
Program.<Main>$(String[] args) line 51
Program.<Main>(String[] args)
InvokeStub_Program.<Main>(Object, Object, IntPtr*)
MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
--- End of stack trace from previous location ---
DeferredHost.StartAsync(CancellationToken cancellationToken)
HostingAbstractionsHostBuilderExtensions.StartAsync(IHostBuilder hostBuilder, CancellationToken cancellationToken)
HostingAbstractionsHostBuilderExtensions.Start(IHostBuilder hostBuilder)
TraffiCaptureFactoryBase.CreateHost(IHostBuilder builder) line 47
WebApplicationFactory`1.ConfigureHostBuilder(IHostBuilder hostBuilder)
WebApplicationFactory`1.EnsureServer()
WebApplicationFactory`1.get_Services()
```

Any idea whats going wrong?

**Comment by dj-nitehawk** [comment]
can you pls try `v5.1.1-beta1`
should be fixed if the assumed cause is correct ;-)

**Comment by szekelymatyas** [comment]
Updated to latest version. Still fails occasionally. Is is possible im doing something wrong? And if yes, do you have any idea what am i doing wrong?

**Comment by dj-nitehawk** [comment]
huh... interesting...
i'm afraid the only way to get to the bottom of this is for you to reference the fastendpoints source code instead of the nuget package and run the tests in debug mode.
then it should break on the exact location where the exeption occurs.
i'm gonna need a file name and line number of the location where the problem occurs.

are you by any chance using rider+xunit combo?
people have reported similar issues with rider+xunit before.
there has been no incidents with visual studio so far.

**Comment by szekelymatyas** [comment]
Im using visual studio with xunit right know. But the problem has occured in rider too, if i remember correctly. Later im gonna pull de source, but right know i have a lot of think to do. The biggest problem is that its only happens 2-3 times in about 100. So im not sure how to reproduce it deterministicly.

**Comment by laya-alsh** [comment]
@szekelymatyas can it be that you run tests in parallel? I also have sometimes an error when i run tests in parallel because the test server is being configured multiple times and (as far as i understood) FE uses many _static_ things during registration.. 
i don't consider it as FE problem (i just need to correct my tests) but maybe it is also relevant to you..

**Comment by dj-nitehawk** [comment]
i've tried to replicate it by creating 100 web application factories simultaneously where each factory also creates 100 http clients parallelly in the attached solution. works without any issues. pls give it a try and see if you guys can replicate any static vars being messed up due to parallelism. this leads me to believe the testing libraries may be doing something weird under the hood. need to know how to reliably replicate it to be able to fix it :-(
[Parallel-Repro.zip](https://github.com/FastEndpoints/Library/files/9566492/Parallel-Repro.zip)

**Comment by laya-alsh** [comment]
i've found the error from the pipeline (if you're curious):
>    System.InvalidOperationException : Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
  Stack Trace:
     at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at FastEndpoints.MainExtensions.MapFastEndpoints(IEndpointRouteBuilder app, Action`1 configAction)
   at FastEndpoints.MainExtensions.UseFastEndpoints(WebApplication app, Action`1 configAction)
   at MYAPP.EndpointsConfiguration.UseEndpoints(WebApplication app)
   
I will try to dig into the problem if it happens next time by me 😄 It happened only 2 times from 130 runs..

**Comment by dj-nitehawk** [comment]
@laya-alsh that stack trace is actually not that helpful as it doesn't offer any clues as to which dictionary got corrupted. the `MapFastEndpoints()` method only has 1 dictionary and it's already a concurrent dictionary. https://github.com/FastEndpoints/Library/blob/fc55e7f870daa3a3716549cba80f9224c3fe8ac6/Src/Library/Extensions/MainExtensions.cs#L75

it must be something deep within that's throwing. no idea how to debug this.

**Comment by szekelymatyas** [comment]
> i've tried to replicate it by creating 100 web application factories simultaneously where each factory also creates 100 http clients parallelly in the attached solution. works without any issues. pls give it a try and see if you guys can replicate any static vars being messed up due to parallelism. this leads me to believe the testing libraries may be doing something weird under the hood. need to know how to reliably replicate it to be able to fix it :-( [Parallel-Repro.zip](https://github.com/FastEndpoints/Library/files/9566492/Parallel-Repro.zip)

I added some request to the sample. I got an exception every second try. Here is my example:
[Parallel-Repro.zip](https://github.com/FastEndpoints/Library/files/9577232/Parallel-Repro.zip)

The exception:
```
Message: 
System.InvalidOperationException : Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.

  Stack Trace: 
Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
MainExtensions.MapFastEndpoints(IEndpointRouteBuilder app, Action`1 configAction)
MainExtensions.UseFastEndpoints(WebApplication app, Action`1 configAction)
Program.Main() line 16
--- End of stack trace from previous location ---
DeferredHost.StartAsync(CancellationToken cancellationToken)
HostingAbstractionsHostExtensions.Start(IHost host)
WebApplicationFactory`1.CreateHost(IHostBuilder builder)
WebApplicationFactory`1.ConfigureHostBuilder(IHostBuilder hostBuilder)
WebApplicationFactory`1.EnsureServer()
<4 more frames...>
<<Test1>b__1>d.MoveNext() line 21
--- End of stack trace from previous location ---
<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
<<Test1>b__0_0>d.MoveNext() line 19
--- End of stack trace from previous location ---
<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
Test.Test1() line 16
--- End of stack trace from previous location ---
```

**Comment by dj-nitehawk** [comment]
@szekelymatyas that was actually helpful to find the culprit. thank you very much!
fixed in `v5.2.0-beta10`
